# Generated by Django 3.2.8 on 2021-10-28 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('cpf', models.CharField(max_length=45)),
                ('cnpj', models.CharField(max_length=45)),
                ('endereco', models.CharField(max_length=45, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=4)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=16)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usinagem', models.BooleanField()),
                ('montagem', models.BooleanField()),
                ('revisao', models.BooleanField(verbose_name='Revisão')),
                ('motor', models.BooleanField()),
                ('cabecote', models.BooleanField(verbose_name='Cabeçote')),
                ('outros', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cliente')),
            ],
        ),
    ]
