# Generated by Django 3.2.9 on 2021-11-14 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('cpf', models.CharField(max_length=45)),
                ('cnpj', models.CharField(max_length=45)),
                ('endereco', models.CharField(max_length=45, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=4)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=16)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=45)),
                ('cod_fabricante', models.CharField(max_length=45)),
                ('qtde_atual', models.IntegerField()),
                ('qtde_minima', models.IntegerField()),
                ('ultima_compra', models.DateField()),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoBiela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medir', models.CharField(max_length=45)),
                ('pesar', models.CharField(max_length=45)),
                ('alinhar', models.CharField(max_length=45)),
                ('bielacol', models.CharField(max_length=45)),
                ('retificar_alojamento_bronzia', models.CharField(max_length=45)),
                ('trocar_bucha', models.CharField(max_length=45)),
                ('retificar_bucha', models.CharField(max_length=45)),
                ('montagem_pistao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoCabecote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaina', models.CharField(max_length=45)),
                ('trocar_guias', models.CharField(max_length=45)),
                ('trocar_sedes_valvulas', models.CharField(max_length=45)),
                ('montagem_valvulas', models.CharField(max_length=45)),
                ('regulagem_valvulas', models.CharField(max_length=45)),
                ('servico_solda', models.CharField(max_length=45)),
                ('teste_hidroestatico', models.CharField(max_length=45)),
                ('banho_quimico', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoComandoValvula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspecionar', models.CharField(max_length=45)),
                ('desempenar', models.CharField(max_length=45)),
                ('polir', models.CharField(max_length=45)),
                ('retificar', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desmontagem', models.CharField(max_length=45)),
                ('limpezaCompleta', models.BooleanField()),
                ('limpezaParcial', models.BooleanField()),
                ('montagemCompleta', models.BooleanField()),
                ('montagem_Parcial', models.BooleanField()),
                ('pintura', models.CharField(max_length=45)),
                ('remocao', models.CharField(max_length=45)),
                ('instalacao', models.CharField(max_length=45)),
                ('servico_motorcol', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoVirabrequim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limpeza', models.CharField(max_length=45)),
                ('teste_trinca_superficial_e_dureza', models.CharField(max_length=45)),
                ('desempenar', models.CharField(max_length=45)),
                ('retificar', models.CharField(max_length=45)),
                ('polir', models.IntegerField()),
                ('balancear', models.CharField(max_length=45)),
                ('tornear_lateral', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoVolante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retificar', models.CharField(max_length=45)),
                ('balancear', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoBloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limpeza', models.CharField(max_length=45)),
                ('brunir_cilindro', models.CharField(max_length=45)),
                ('retificar_cilindro', models.CharField(max_length=45)),
                ('encamisar_cilindro', models.CharField(max_length=45)),
                ('madrilhar_buchar_comando_valvula', models.CharField(max_length=45)),
                ('mandrilhar_mancais', models.CharField(max_length=45)),
                ('mandrilhar_comando_val_auxiliar', models.CharField(max_length=45)),
                ('plainar', models.CharField(max_length=45)),
                ('adaptar_retentor_polia_carcaca', models.CharField(max_length=45)),
                ('embuchar_mancal_traseiro_carcaca', models.CharField(max_length=45)),
                ('fresar_alojamento_tucho_carcaca', models.CharField(max_length=45)),
                ('cabecote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.servicocabecote')),
                ('virabrequim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.servicovirabrequim')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usinagem', models.BooleanField()),
                ('montagem', models.BooleanField()),
                ('revisao', models.BooleanField(verbose_name='Revisão')),
                ('motorCompleto', models.BooleanField()),
                ('cabecote', models.BooleanField(verbose_name='Cabeçote')),
                ('outros', models.CharField(max_length=20)),
                ('biela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.servicobiela')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.servicobloco')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente')),
                ('comandoValvula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.servicocomandovalvula')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.servicomotor')),
                ('volante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.servicovolante')),
            ],
        ),
    ]
