# Generated by Django 3.2.9 on 2021-11-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
