# Generated by Django 3.2.9 on 2021-11-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211114_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordem',
            name='id',
        ),
        migrations.AlterField(
            model_name='ordem',
            name='numeroordem',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
