# Generated by Django 3.2.9 on 2021-11-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211116_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
