from os import truncate
from django.conf import settings
from django.db import models

# Create your models here.
class Cliente(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    nome = models.CharField(max_length=45)
    cpf = models.CharField(max_length=18, blank=True, null=True, unique=True)
    cnpj = models.CharField(max_length=18, blank=True, null=True, unique=True)
    email = models.EmailField(blank=True, null=True)
    endereco = models.CharField(max_length=45, verbose_name='Endereço')
    bairro = models.CharField(max_length=45)
    cidade = models.CharField(max_length=45)
    estado = models.CharField(max_length=2)
    cep = models.CharField(max_length=10)
    telefone = models.CharField(max_length=16)

    def __str__(self):
        return "{}".format(self.nome)

class Ordem(models.Model):
    id = models.AutoField(primary_key=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.PROTECT)
    data_entrada = models.DateField()
    data_saida = models.DateField(blank=True, null=True)
    numero_chassi = models.CharField(max_length=25, blank=True, null=True)
    numero_bloco = models.CharField(max_length=25, blank=True, null=True)
    modelo_motor = models.CharField(max_length=50, blank=True, null=True)
    pistaocanel = models.BooleanField(default=False)
    pistaocanelq = models.IntegerField(blank=True, null=True)
    pistaocaneld = models.CharField(max_length=15, blank=True, null=True)
    aneispistao = models.BooleanField(default=False)
    aneispistaoq = models.IntegerField(blank=True, null=True)
    aneispistaod = models.CharField(max_length=15, blank=True, null=True)
    retentortras = models.BooleanField(default=False)
    retentortrasq = models.IntegerField(blank=True, null=True)
    retentortrasd = models.CharField(max_length=15, blank=True, null=True)
    kitsmotor = models.BooleanField(default=False)
    kitsmotorq = models.IntegerField(blank=True, null=True)
    kitsmotord = models.CharField(max_length=15, blank=True, null=True)
    bronzbiela = models.BooleanField(default=False)
    bronzbielaq = models.IntegerField(blank=True, null=True)
    bronzbielad = models.CharField(max_length=15, blank=True, null=True)
    bronzinamancal = models.BooleanField(default=False)
    bronzinamancalq = models.IntegerField(blank=True, null=True)
    bronzinamancald = models.CharField(max_length=15, blank=True, null=True)
    buchacomando = models.BooleanField(default=False)
    buchacomandoq = models.IntegerField(blank=True, null=True)
    buchacomandod = models.CharField(max_length=15, blank=True, null=True)
    buchabiela = models.BooleanField(default=False)
    buchabielaq = models.IntegerField(blank=True, null=True)
    buchabielad = models.CharField(max_length=15, blank=True, null=True)
    parafusobiela = models.BooleanField(default=False)
    parafusobielaq = models.IntegerField(blank=True, null=True)
    parafusobielad = models.CharField(max_length=15, blank=True, null=True)
    meialua = models.BooleanField(default=False)
    meialuaq = models.IntegerField(blank=True, null=True)
    meialuad = models.CharField(max_length=15, blank=True, null=True)
    jogojuntas = models.BooleanField(default=False)
    jogojuntasq = models.IntegerField(blank=True, null=True)
    jogojuntasd = models.CharField(max_length=15, blank=True, null=True)
    retentordiant = models.BooleanField(default=False)
    retentordiantq = models.IntegerField(blank=True, null=True)
    retentordiantd = models.CharField(max_length=15, blank=True, null=True)
    retentortras = models.BooleanField(default=False)
    retentortrasq = models.IntegerField(blank=True, null=True)
    retentortrasd = models.CharField(max_length=15, blank=True, null=True)
    sedesescape = models.BooleanField(default=False)
    sedesescapeq = models.IntegerField(blank=True, null=True)
    sedesescaped = models.CharField(max_length=15, blank=True, null=True)
    sedesadmissao = models.BooleanField(default=False)
    sedesadmissaoq = models.IntegerField(blank=True, null=True)
    sedesadmissaod = models.CharField(max_length=15, blank=True, null=True)
    guiasescape = models.BooleanField(default=False)
    guiasescapeq = models.IntegerField(blank=True, null=True)
    guiasescaped = models.CharField(max_length=15, blank=True, null=True)
    guiasadmissao = models.BooleanField(default=False)
    guiasadmissaoq = models.IntegerField(blank=True, null=True)
    guiasadmissaod = models.CharField(max_length=15, blank=True, null=True)
    valvulasescape = models.BooleanField(default=False)
    valvulasescapeq = models.IntegerField(blank=True, null=True)
    valvulasescaped = models.CharField(max_length=15, blank=True, null=True)
    valvulasadmissao = models.BooleanField(default=False)
    valvulasadmissaoq = models.IntegerField(blank=True, null=True)
    valvulasadmissaod = models.CharField(max_length=15, blank=True, null=True)
    chavetas = models.BooleanField(default=False)
    chavetasq = models.IntegerField(blank=True, null=True)
    chavetasd = models.CharField(max_length=15, blank=True, null=True)
    molas = models.BooleanField(default=False)
    molasq = models.IntegerField(blank=True, null=True)
    molasd = models.CharField(max_length=15, blank=True, null=True)
    pratos = models.BooleanField(default=False)
    pratosq = models.IntegerField(blank=True, null=True)
    pratosd = models.CharField(max_length=15, blank=True, null=True)
    calcos = models.BooleanField(default=False)
    calcosq = models.IntegerField(blank=True, null=True)
    calcosd = models.CharField(max_length=15, blank=True, null=True)
    vedadores = models.BooleanField(default=False)
    vedadoresq = models.IntegerField(blank=True, null=True)
    vedadoresd = models.CharField(max_length=15, blank=True, null=True)
    tuchosvalvulas = models.BooleanField(default=False)
    tuchosvalvulasq = models.IntegerField(blank=True, null=True)
    tuchosvalvulasd = models.CharField(max_length=15, blank=True, null=True)
    varetasvalvulas = models.BooleanField(default=False)
    varetasvalvulasq = models.IntegerField(blank=True, null=True)
    varetasvalvulasd = models.CharField(max_length=15, blank=True, null=True)
    porcareguladora = models.BooleanField(default=False)
    porcareguladoraq = models.IntegerField(blank=True, null=True)
    porcareguladorad = models.CharField(max_length=15, blank=True, null=True)
    reglbalanceiro = models.BooleanField(default=False)
    reglbalanceiroq = models.IntegerField(blank=True, null=True)
    reglbalanceirod = models.CharField(max_length=15, blank=True, null=True)
    comandovalvula = models.BooleanField(default=False)
    comandovalvulaq = models.IntegerField(blank=True, null=True)
    comandovalvulad = models.CharField(max_length=15, blank=True, null=True)
    engrcomando = models.BooleanField(default=False)
    engrcomandoq = models.IntegerField(blank=True, null=True)
    engrcomandod = models.CharField(max_length=15, blank=True, null=True)
    flangecomando = models.BooleanField(default=False)
    flangecomandoq = models.IntegerField(blank=True, null=True)
    flangecomandod = models.CharField(max_length=15, blank=True, null=True)
    chavetacomando = models.BooleanField(default=False)
    chavetacomandoq = models.IntegerField(blank=True, null=True)
    chavetacomandod = models.CharField(max_length=15, blank=True, null=True)
    eixobalanceiro = models.BooleanField(default=False)
    eixobalanceiroq = models.IntegerField(blank=True, null=True)
    eixobalanceirod = models.CharField(max_length=15, blank=True, null=True)
    buchabalanceiro = models.BooleanField(default=False)
    buchabalanceiroq = models.IntegerField(blank=True, null=True)
    buchabalanceirod = models.CharField(max_length=15, blank=True, null=True)
    balanceiro = models.BooleanField(default=False)
    balanceiroq = models.IntegerField(blank=True, null=True)
    balanceirod = models.CharField(max_length=15, blank=True, null=True)
    suportebalanceiro = models.BooleanField(default=False)
    suportebalanceiroq = models.IntegerField(blank=True, null=True)
    suportebalanceirod = models.CharField(max_length=15, blank=True, null=True)
    parafbalanceiro = models.BooleanField(default=False)
    parafbalanceiroq = models.IntegerField(blank=True, null=True)
    parafbalanceirod = models.CharField(max_length=15, blank=True, null=True)
    travabalanceiro = models.BooleanField(default=False)
    travabalanceiroq = models.IntegerField(blank=True, null=True)
    travabalanceirod = models.CharField(max_length=15, blank=True, null=True)
    valvulapressao = models.BooleanField(default=False)
    valvulapressaoq = models.IntegerField(blank=True, null=True)
    valvulapressaod = models.CharField(max_length=15, blank=True, null=True)
    peneira = models.BooleanField(default=False)
    peneiraq = models.IntegerField(blank=True, null=True)
    peneirad = models.CharField(max_length=15, blank=True, null=True)
    bombaoleio = models.BooleanField(default=False)
    bombaoleioq = models.IntegerField(blank=True, null=True)
    bombaoleiod = models.CharField(max_length=15, blank=True, null=True)
    bombaagua = models.BooleanField(default=False)
    bombaaguaq = models.IntegerField(blank=True, null=True)
    bombaaguad = models.CharField(max_length=15, blank=True, null=True)
    suportebba = models.BooleanField(default=False)
    suportebbaq = models.IntegerField(blank=True, null=True)
    suportebbad = models.CharField(max_length=15, blank=True, null=True)
    valvtermostatica = models.BooleanField(default=False)
    valvtermostaticaq = models.IntegerField(blank=True, null=True)
    valvtermostaticad = models.CharField(max_length=15, blank=True, null=True)
    bocalagua = models.BooleanField(default=False)
    bocalaguaq = models.IntegerField(blank=True, null=True)
    bocalaguad = models.CharField(max_length=15, blank=True, null=True)
    cxvalvtermost = models.BooleanField(default=False)
    cxvalvtermostq = models.IntegerField(blank=True, null=True)
    cxvalvtermostd = models.CharField(max_length=15, blank=True, null=True)
    mangvalvtermost = models.BooleanField(default=False)
    mangvalvtermostq = models.IntegerField(blank=True, null=True)
    mangvalvtermostd = models.CharField(max_length=15, blank=True, null=True)
    arruelasmancal = models.BooleanField(default=False)
    arruelasmancalq = models.IntegerField(blank=True, null=True)
    arruelasmancald = models.CharField(max_length=15, blank=True, null=True)
    mangbba = models.BooleanField(default=False)
    mangbbaq = models.IntegerField(blank=True, null=True)
    mangbbad = models.CharField(max_length=15, blank=True, null=True)
    cremalheira = models.BooleanField(default=False)
    cremalheiraq = models.IntegerField(blank=True, null=True)
    cremalheirad = models.CharField(max_length=15, blank=True, null=True)
    parafvolante = models.BooleanField(default=False)
    parafvolanteq = models.IntegerField(blank=True, null=True)
    parafvolanted = models.CharField(max_length=15, blank=True, null=True)
    parafcabecote = models.BooleanField(default=False)
    parafcabecoteq = models.IntegerField(blank=True, null=True)
    parafcabecoted = models.CharField(max_length=15, blank=True, null=True)
    colarengr = models.BooleanField(default=False)
    colarengrq = models.IntegerField(blank=True, null=True)
    colarengrd = models.CharField(max_length=15, blank=True, null=True)
    chavvirarbequim = models.BooleanField(default=False)
    chavvirarbequimq = models.IntegerField(blank=True, null=True)
    chavvirarbequimd = models.CharField(max_length=15, blank=True, null=True)
    varetaoleo = models.BooleanField(default=False)
    varetaoleoq = models.IntegerField(blank=True, null=True)
    varetaoleod = models.CharField(max_length=15, blank=True, null=True)
    engrvirabrequim = models.BooleanField(default=False)
    engrvirabrequimq = models.IntegerField(blank=True, null=True)
    engrvirabrequimd = models.CharField(max_length=15, blank=True, null=True)
    pistaocompressor = models.BooleanField(default=False)
    pistaocompressorq = models.IntegerField(blank=True, null=True)
    pistaocompressord = models.CharField(max_length=15, blank=True, null=True)
    aneiscompressor = models.BooleanField(default=False)
    aneiscompressorq = models.IntegerField(blank=True, null=True)
    aneiscompressord = models.CharField(max_length=15, blank=True, null=True)
    bronzbielacompr = models.BooleanField(default=False)
    bronzbielacomprq = models.IntegerField(blank=True, null=True)
    bronzbielacomprd = models.CharField(max_length=15, blank=True, null=True)
    buchabielacompr = models.BooleanField(default=False)
    buchabielacomprq = models.IntegerField(blank=True, null=True)
    buchabielacomprd = models.CharField(max_length=15, blank=True, null=True)
    reparocompressor = models.BooleanField(default=False)
    reparocompressorq = models.IntegerField(blank=True, null=True)
    reparocompressord = models.CharField(max_length=15, blank=True, null=True)
    buchamancalcompr = models.BooleanField(default=False)
    buchamancalcomprq = models.IntegerField(blank=True, null=True)
    buchamancalcomprd = models.CharField(max_length=15, blank=True, null=True)
    mangueira = models.BooleanField(default=False)
    mangueiraq = models.IntegerField(blank=True, null=True)
    mangueirad = models.CharField(max_length=15, blank=True, null=True)
    camisacil = models.BooleanField(default=False)
    camisacilq = models.IntegerField(blank=True, null=True)
    camisacild = models.CharField(max_length=15, blank=True, null=True)
    abracadeira = models.BooleanField(default=False)
    abracadeiraq = models.IntegerField(blank=True, null=True)
    abracadeirad = models.CharField(max_length=15, blank=True, null=True)
    repcompressorsup = models.BooleanField(default=False)
    repcompressorsupq = models.IntegerField(blank=True, null=True)
    repcompressorsupd = models.CharField(max_length=15, blank=True, null=True)
    repcompressorinf = models.BooleanField(default=False)
    repcompressorinfq = models.IntegerField(blank=True, null=True)
    repcompressorinfd = models.CharField(max_length=15, blank=True, null=True)
    filtrolubrificante = models.BooleanField(default=False)
    filtrolubrificanteq = models.IntegerField(blank=True, null=True)
    filtrolubrificanted = models.CharField(max_length=15, blank=True, null=True)
    valvfiltrolubrif = models.BooleanField(default=False)
    valvfiltrolubrifq = models.IntegerField(blank=True, null=True)
    valvfiltrolubrifd = models.CharField(max_length=15, blank=True, null=True)
    camisacil = models.BooleanField(default=False)
    camisacilq = models.IntegerField(blank=True, null=True)
    camisacild = models.CharField(max_length=15, blank=True, null=True)
    outraspeca = models.TextField(max_length=1000, blank=True, null=True)
    componetes = models.CharField(max_length=50, blank=True, null=True)
    turbina = models.BooleanField(default=False)
    ccarter = models.BooleanField(default=False)
    cbujao = models.BooleanField(default=False)
    ccapas = models.BooleanField(default=False)
    cparafuros = models.BooleanField(default=False)
    cparafurosq = models.IntegerField(blank=True, null=True)
    bulbotemp = models.BooleanField(default=False)
    alternador = models.BooleanField(default=False)
    arranquemont = models.BooleanField(default=False)
    cpeneira = models.BooleanField(default=False)
    bombahidr = models.BooleanField(default=False)
    cflexivel = models.BooleanField(default=False)
    polia = models.BooleanField(default=False)
    tuboadmissao = models.BooleanField(default=False)
    tuboescape = models.BooleanField(default=False)
    carcaca = models.BooleanField(default=False)
    volante = models.BooleanField(default=False)
    plato = models.BooleanField(default=False)
    friccao = models.BooleanField(default=False)
    parafcarter = models.BooleanField(default=False)
    parafcarterq = models.IntegerField(blank=True, null=True)
    tampadistr = models.BooleanField(default=False)
    tampavalvulas = models.BooleanField(default=False)
    tampalateral = models.BooleanField(default=False)
    bielas = models.BooleanField(default=False)
    cpistao = models.BooleanField(default=False)
    comando = models.BooleanField(default=False)
    cpolia = models.BooleanField(default=False)
    suportemotor = models.BooleanField(default=False)
    canovareta = models.BooleanField(default=False)
    filtrocomb = models.BooleanField(default=False)
    acelerador = models.BooleanField(default=False)